/*
 * This source file was generated by the Gradle 'init' task
 */
package taller3;

public class App {

   public static void main(String[] args) {
   try {
      System.out.println(Escribir_asc(3, 5, 2));
      System.out.println(Obtener_cifras(10));
      System.out.println(Clasificar_char('a'));
      System.out.println(Hallar_division_exacta(10, 5));
      System.out.println(Consultar_hab((byte)1, "VE"));
      System.out.println(Obtener_obs(true, false, false));
      System.out.println(Conocer_invitacion("verde"));
   } catch (Exception e) {
      
   }

   }

   /*
    * 1. Construya un algoritmo e implemente la función en Java Escribir_asc que
    * reciba tres números enteros diferentes
    * y devuelva en un String en orden ascendente con el siguiente formato:
    * "##### - ##### - #####", donde el primero es
    * el mayor de todos, el segundo el del medio, el tercero el menor de todos. Si
    * hay al menos dos números iguales,
    * devolverá el mensaje: "Error: La función no considera números iguales". Si
    * hay un error inesperado, deberá mostrar
    * el mensaje: "Ocurrió un error inesperado".
    */
public static String Escribir_asc(int a, int b, int c) {
   try {
         String mensaje = "";

         if (a != b && a != c && b != c) {
              if (a > b && b > c) {
                  mensaje = a + " - " + b + " - " + c;
      } 
         else if (a > c && c > b) {
                  mensaje = a + " - " + c + " - " + b;
      } 
         else if (b > a && a > c) {
                  mensaje = b + " - " + a + " - " + c;
      } 
         else if (b > c && c > a) {
                  mensaje = b + " - " + c + " - " + a;
      }
          else if (c > a && a > b) {
                  mensaje = c + " - " + a + " - " + b;
      } 
         else if (c > a && b > a) {
                  mensaje = c + " - " + b + " - " + a;
      }
              return mensaje;
      } else {
            return "Error: La función no considera números iguales";
              
      }
      } catch (Exception e) {
         return "Ocurrió un error inesperado";
          
      }
   

      
}





   /*
    * 2. Construya un algoritmo e implemente la función en Java Obtener_cifras que
    * recibe un número entre 0 y 50.000
    * y devuelve byte con las cifras que tiene. Por ejemplo 10 tiene dos cifras,
    * 9999 tiene 4 cifras. Si el número
    * no está en el rango devuelve 0. Y si hay un error inesperado, devuelve -1.
    * 
    */
public static byte Obtener_cifras(int numero){
   try {
      byte resultado = 0; 
      final int a = 10, b = 100, c=1000, d=10000, e=50000, no_valido = 0, nro_1 = 1, nro_2 = 2, nro_3 = 3, nro_4 = 4, nro_5 = 5;

      if(no_valido <= numero && numero <= e){

         if(no_valido <= numero && numero < a){
            resultado = nro_1;

   }
      else if(a <= numero && numero < b){
         resultado = nro_2; 
   }
      else if(b <= numero && numero < c){
         resultado = nro_3;
   } 
      else if(c <= numero && numero < d){
         resultado = nro_4;
   }
      else if(d <= numero && numero < e){
         resultado = nro_5;
         
   }

      else{
         return -1;
   }
   }
      else{
         return 0;
   }
         return resultado;

    


   }catch (Exception e) {
      return -1;
   }

}



   /*
    * 3. Construya un algoritmo e implemente la función en Java Clasificar_char que
    * recibe un caracter, y
    * devuelve un string de acuerdo con las siguientes condiciones: si es un
    * alfabético, deuvelve "ES LETRA";
    * si es numérico, devuelve "ES NUMERO" o si es un carácter especial, devuelve
    * "ESPECIAL".
    * Los caracteres se validan de acuerdo con la tabla ascii básica y lo explicado
    * en clase.
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    * 
    */
public static String Clasificar_char(char caracter){
   try {
        String mensaje = "";
        int codigo_Ascii = (int) caracter;
        final int a = 33, b = 255, c = 65, d = 122, e = 48, f = 57, g = 32, h= 47, i = 58, j = 64, k = 123, l = 126;

         if(caracter >= a && caracter <= b){

         if(caracter >= c && caracter <= d){
            mensaje = "ES LETRA";
   }
         else if(caracter >= e && caracter <= f){

            mensaje = "ES NUMERO";
   }
         else if(caracter >= g && caracter <= h || caracter >= i && caracter <= j || caracter >= k && caracter <= l ){

            mensaje = "ESPECIAL";
   }

   }
        else {
         return "Ocurrió un error inesperado";
   }
         return mensaje;

   } catch (Exception e) {
         return "Ocurrió un error inesperado";
   }
}

   /*
    * 
    * 4. Construya un algoritmo e implemente la función en Java
    * Hallar_division_exacta que pida dos números enteros,
    * calcule la división del primero sobre el segundo, y al final si la división
    * es exacta, devuelva "DIVISION EXACTA"
    * y de lo contrario devuelva "DIVISION NO EXACTA". (Exacta significa que tiene
    * cociente, pero no residuo).
    * 
    * Si alguno de los dos números que recibe es cero o negativo, devuelva
    * "NO SE ADMITE CERO O NEGATIVOS".
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    * Nota: Revise el funcionamiento del operador mod que le puede ayudar.
    * 
    * 
    * 
    */
public static String Hallar_division_exacta(int n1, int n2){
   try {
      String resultado = "";

      if(n1 <= 0 || n2 <= 0){
         resultado = "NO SE ADMITE CERO O NEGATIVOS";
   }
      else if(n1 % n2 == 0){
         resultado = "DIVISION EXACTA";
   }
      else if(n1 % n2 != 0){
         resultado = "DIVISION NO EXACTA";
   }

   else{
         return "NO SE ADMITE CERO O NEGATIVOS";
   }

         return resultado;

   } catch (Exception e) {
         return "Ocurrió un error inesperado";
   }

}

   

   /*
    * 5. En la siguiente tabla se encuentra la información de las habitaciones de
    * una finca hotel:
    * 
    * Habitación Camas Planta    AA/VENTILADOR
    *    101         2     Primera     AA
    *    102         1     Primera     VE
    *    201         3     Segunda     AA
    *    202         2     Segunda     VE
    *    301         2     Tercera     AA
    * 
    * 
    * Construya un algoritmo e implemente la función en Java Consultar_hab que
    * reciba en un byte el número de camas
    * y en un string si desea VE o AA, y deuvelva en un texto el o los números de
    * habitación que cumplen ese requisito.
    * Si son varias habitaciones, devuelvalas separadas por el caracter |
    * (normalmente, al lado izquierdo de la tecla del 1).
    * Ejemplo: "101|301"
    * Si el número de camas no está entre 1 y 3 o el string es diferente a AA o VE,
    * devuelva "DATOS NO VÁLIDOS".
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    */
public static  String Consultar_hab(byte camas,String opcion){
   try {
      String mensaje = "";
      final byte cama_a = 2, cama_b = 1, cama_c = 3, no_valido = 0, no_valido2 = 4;
      final String VE = "VE", AA="AA";

      if(camas >= no_valido && no_valido2 >= camas || "VE".equals(opcion) || "AA".equals(opcion) ){

         if(camas == cama_a && "AA".equals(opcion)){
               mensaje = "101|301";
   }
         else if(camas == cama_a && "VE".equals(opcion)){
            mensaje = "202";
   }
         else if(camas == cama_b && "VE".equals(opcion)){
            mensaje = "102";
   }
         else if(camas == cama_c && "AA".equals(opcion)){
            mensaje = "201";
    }

         return mensaje;

   }
      else{
         return "DATOS NO VÁLIDOS";
   }

   } catch (Exception e) {
      return "Ocurrió un error inesperado";
   }
}

   
   /*
    * 
    * 6. Un restaurante vende 3 platos. Si el cliente solicita el plato 1, le dan
    * el postre gratis; si selecciona los platos
    * 1 y 2, le dan la bebida gratis y si selecciona los platos 1,2 y 3, le dan
    * postre y bebida.
    * Construya un algoritmo e implemente la función Obtener_obs en Java que reciba
    * 3 booleanos, uno para cada plato y en
    * un String devuelva el obsequio ganado en mayúscula, así: "BEBIDA", "POSTRE",
    * "BEBIDA Y POSTRE".
    * Si los 3 platos vienen en false, , devuelva "PLATOS NO VÁLIDOS".
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    */
public static String Obtener_obs(boolean p1, boolean p2, boolean p3){
   try {
      String mensaje = "";

      if(p1== false && p2 == false && p3 == false){
         return "PLATOS NO VÁLIDOS";
   }
      else if(p1 == true && p2 == false && p3 == false){
         mensaje = "POSTRE";
   }
      else if(p1 == true && p2 == true && p3 == false){
         mensaje = "BEBIDA";
   }
      else if(p1 == true && p2 == true && p3 == true){
         mensaje = "BEBIDA Y POSTRE";
   }

         return mensaje;



   } catch (Exception e) {
   return "Ocurrió un error inesperado";
   }

}


   /*
    * 7. Un grupo de amigos hace un sorteo semanalmente con pelotas de ping pong,
    * para saber quién invita y a qué  la próxima salida.
    * Las opciones dependen del color que sacan en cada bola y son:
    * 
    * verde: Invita a las cervezas
    * azul: Invita a la pizza
    * rojo: Invita al postre
    * amarillo: Paga el parqueadero de todos
    * blanco o negro: Vaya y disfrute
    * Si la función recibe algo diferente a los colores dados, debe retornar
    * "Error en el color".
    * 
    * Se necesita una función en java Conocer_invitacion que reciba un string con
    * el color de la bola y retorna un
    * String con exactamente el texto de la invitación correspondiente.
    * 
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    * 
    */
public static String Conocer_invitacion(String color){
   try {
      String mensaje = "";



   switch (color) {
      case "verde":
                    mensaje = "Invita a las cervezas";
                    break;
      case "azul":
                    mensaje = "Invita a la pizza";
                    break;
       case "rojo":
                    mensaje = "Invita al postre";
                    break;
      case "amarillo":
                    mensaje = "Paga el parqueadero de todos";
                    break;
      case "blanco":
      case "negro":
                    mensaje = "Vaya y disfrute";
                    break;
   default:
                    mensaje = "Error en el color";
                    break;
            
   }

   return mensaje;

   } catch (Exception e) {
      return "Ocurrió un error inesperado";
   }
   
}
}
